apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::349110610264:role/eksctl-demo-cluster-1-cluster-ServiceRole-TfrXhExmbICq
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::349110610264:role/codebuild-WEBAPP-PROJECT-DEVs-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::349110610264:user/altamash
      username: altamash
      groups:
        - system:masters


kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system